baseURL = 'https://k5cv.com/'
languageCode = 'en-us'
title = 'K5CV | Cliff'
theme = "hugo-theme-relearn"

defaultContentLanguage = "en-us"
enableInlineShortcodes = true

# Enable emojis globally
enableEmoji = true

[params]
  # Relearn theme params
  author.name = "Cliff Colvin"
  description = "Cliff Colvin | K5CV"
  themeVariant = "relearn-dark"
  disableLandingPageButton = true
  showVisitedLinks = true

  [params.social]
    github = "cliffcolvin"
    twitter = "cliff_colvin"
    rss = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[outputs]
  home = ["html", "rss", "search"]

[module]
  [module.mounts]
    source = "content"
    target = "content"
